version: "3.7"
services:

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "9000:8080"

  db:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pingo
